### ISSUE TITLE
Does this plugin support Multiple Devices?

### ISSUE THREAD

**Issue by machineglow** [codyc1515/homebridge-orbit-bhyve#1]
Hi,  

First off, I'm considering purchasing b-hyve products and run homekit at home.  Before I pull the trigger, I have a few questions:

1) Does this plugin support multiple devices, in particular:

The 4-zone indoor wifi timer:
https://bhyve.orbitonline.com/indoor-timer/

and the BT hose valve?
https://bhyve.orbitonline.com/hosefaucet/

2) Would each zone + the BT valve be presented as separate homekit switches/valves?

3) What setup do you currently run this plugin with?

Thank you for your work and looking forward to joining the cause.  

Thanks!

**Comment by mokrol** [comment]
I have the 8-zone and I can't get it to work at all.

**Comment by codyc1515** [comment]
You will be impressed with the Orbit app with regards to the automation that it offers, although the design is (IMO) a bit lacking. However this plug-in is more made for if you want to tell Siri to turn the tap on for a bit.

Currently the BT Hose Valve is the only one supported. I am waiting for someone to contact me who has purchased the 4 or 8 zone device so that I can add support for it.

:)

**Comment by d4ni37** [comment]
@codyc1515 Is it possible to support multiple BT Hose Valves? I have one in my backyard, and one in my front yard. Great work beating Orbit to getting HomeKit compatibility.

**Comment by codyc1515** [comment]
@d4ni37 Yes, you can. Just add the accessory multiple times in your config.json file. You will probably need two accounts to do so as it will just pick the first device.

Everyone else, I am still working on the multi-zone support. This seems to be working, but I need some more time to do testing on it. It should arrive soon.

**Comment by codyc1515** [comment]
I have added support for multi-zone controllers now. However, there is currently still only support for one device. I am limited in my experience with the platform support in Homebridge or I would be able to add this fairly easily. I wasted at least one day working on this. Until the documentation is improved regrettably I am unable to help in this respect.

Simply change your config.json file to reflect something similar to the following to add the extra zones:

        {
            "accessory": "OrbitBHyve",
            "name": "Orbit B-Hyve",
            "email": "joe@bloggs.com",
            "password": "mySECUREpassword",
            "zones": 4
        }
Please let me know your feedback once you have had a chance to try it.

An important note: the Orbit API only allows one Zone to be running at a time, even though HomeKit supports multiple. This means when you turn on one zone, it will turn off the others. Disappointing but still good to have the control over the other zones.

I am also aware that there appears to be an issue with the Remaining Duration, but this seems to be a somewhat minor issue.
