### ISSUE TITLE
Default run time

### ISSUE THREAD

**Issue by dodavies** [codyc1515/homebridge-orbit-bhyve#13]
Default run time is reporting as five minutes, changing this within home is accepted but makes no difference, i.e setting to 15  minutes it reverts to 5 minutes or not set so defaulting to 5 minutes.
Log reports
Unknown preset runtime, leaving default of 5 minutes

**Comment by mitch7391** [comment]
I have the same problem, maybe we could get it added to the config?

**Comment by codyc1515** [comment]
The value is read from the Orbit service, but not written (yet!). Workaround: set the time in the Orbit app.
