### ISSUE TITLE
crashes homekit on startup

### ISSUE THREAD

**Issue by cookswim** [codyc1515/homebridge-orbit-bhyve#17]
I tried to recently add a b hyve faucet timer to my homebridge setup, but it crashes homebridge on startup.
I'm using this configuration under the accessories part of the config.json file

> {
>         "accessory" : "OrbitBHyve",
>         "name"      : "Orbit B-Hyve", 
>         "username"  : "my@email.address",
>         "password"  : "mypassword", 
>         "zones"     : 1
> }

partial startup log.

> May 16 16:57:21 atv homebridge[1815]: [2020-5-16 16:57:21] Error: The requested accessory 'OrbitBHyve' was not registered by any plugin.
> May 16 16:57:21 atv homebridge[1815]: at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:64:13)
> May 16 16:57:21 atv homebridge[1815]: at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:297:42)
> May 16 16:57:21 atv homebridge[1815]: at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
> May 16 16:57:21 atv homebridge[1815]: at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
> May 16 16:57:21 atv homebridge[1815]: at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
> May 16 16:57:21 atv homebridge[1815]: at Module._compile (module.js:653:30)
> May 16 16:57:21 atv homebridge[1815]: at Object.Module._extensions..js (module.js:664:10)
> May 16 16:57:21 atv homebridge[1815]: at Module.load (module.js:566:32)
> May 16 16:57:21 atv homebridge[1815]: at tryModuleLoad (module.js:506:12)
> May 16 16:57:21 atv homebridge[1815]: at Function.Module._load (module.js:498:3)
> May 16 16:57:21 atv homebridge[1815]: at Function.Module.runMain (module.js:694:10)
> May 16 16:57:21 atv homebridge[1815]: at startup (bootstrap_node.js:204:16)
> May 16 16:57:21 atv homebridge[1815]: at bootstrap_node.js:625:3
> May 16 16:57:21 atv homebridge[1815]: [2020-5-16 16:57:21] Got SIGTERM, shutting down Homebridge...

**Comment by codyc1515** [comment]
Can you please post the full log and config (redacted)?

**Comment by mitch7391** [comment]
@cookswim this fork might work for you:

https://github.com/MortJC/homebridge-platform-orbit
