### ISSUE TITLE
Siri is giving the wrong response but doing the right thing.

### ISSUE THREAD

**Issue by Priva28** [codyc1515/homebridge-orbit-bhyve#2]
When I ask Siri to turn on my sprinkler for a certain amount of time she tells me that she has “stopped watering”. Everything else works great! I’m not sure if this is an Apple issue or not but it does it on all my devices.

**Comment by bostaunieux** [comment]
I’m seeing the same thing. Works great otherwise, though.

**Comment by jianyu-li** [comment]
What controller do you use with this? Does it show up as a sprinkler in the home app?

**Comment by bostaunieux** [comment]
I’m using this https://www.amazon.com/dp/B0758NR8DJ/ and it shows up as a sprinkler in the home app.

**Comment by codyc1515** [comment]
I have a bit of an issue with this as well. Was having a play with Siri on the HomePod today, but even on my iPhone it does the same thing. I will have to try it with the HomeKit Accessory Simulator and see if it is still buggy there. I will report back.

**Comment by codyc1515** [comment]
I have just tried it now and it seems like this is definitely a bug. If you use the HomeKit Accessory Simulator, add the Irrigation System service, then ask Siri to turn on / off the system. Siri always does the opposite of what you expect. I have filed a Feedback with Apple now.

**Comment by bostaunieux** [comment]
Just adding a datapoint, I have the Rachio 3 controller with native HomeKit support and it doesn’t have this issue. It’s a multi-zone controller so differs from how the Orbit one works, though.

For turning on one zone, Siri responds with “OK, the <zone> is queued up for watering”

Turn off all zones responds with “OK, I’ve stopped watering your valves” and a single zone off responds with “OK, I’ve stopped watering your <zone>”.

**Comment by codyc1515** [comment]
Interesting. I have not heard back from Apple on any of the 12 HomeKit & Home app-related bugs that I have filed with them. So I am not really able to do anything about it at this stage. As I explained before as we'll it is happening with the HomeKit Accessory Simulator which comes directly from Apple. I'm not sure what exactly it could be.

**Comment by codyc1515** [comment]
I still have had no response from Apple so I'm going to close this one for now as a known issue.
