### ISSUE TITLE
Does this work with the b-hyve 57915? Does it appear as a sprinkler?

### ISSUE THREAD

**Issue by jianyu-li** [codyc1515/homebridge-orbit-bhyve#3]
Does this plugin work with this [Controller](https://smile.amazon.com/dp/B07DJ2QTW9/ref=nav_timeline_asin?_encoding=UTF8&psc=1)? Does it appear in the home app as a standard sprinkler? Thanks!

**Comment by codyc1515** [comment]
We can maybe add support for it. I have never seen this one before.

If you do end up buying it, please set it up in the Orbit B-Hyve app and send your login details to codyc1515@icloud.com then I can have a look at adding support. I cannot guarantee that I will be able to make it work but it looks like they are all using the same app so should be fine.

:)

**Comment by codyc1515** [comment]
I have added support for multi-zone controllers now. Simply change your config.json file to reflect something similar to the following:

```
        {
            "accessory": "OrbitBHyve",
            "name": "Orbit B-Hyve",
            "email": "joe@bloggs.com",
            "password": "mySECUREpassword",
            "zones": 4
        }
```

Please let me know your feedback once you have had a chance to try it.

An important note: the Orbit API only allows one Zone to be running at a time, even though HomeKit supports multiple. This means when you turn on one zone, it will turn off the others. Disappointing but still good to have the control over the other zones.

I am also aware that there appears to be an issue with the Remaining Duration, but this seems to be a somewhat minor issue.
