### ISSUE TITLE
Sprinkler giving Characteristic warnings

### ISSUE THREAD

**Issue by mcuthbert** [codyc1515/homebridge-orbit-bhyve#5]
G'day,
I have a B-Hyve sprinkler and wireless device, when I attempt to add it Homebridge recognises it as a B-Hyve sprinkler but I am unable to add it in the Home app.  Homebridge throws the following error code: "HAP WARNING: Characteristic 000000D1-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000D0-0000-1000-8000-0026BB765291.  Adding anyway."

My wireless key is model 96506

Is there any way to expand the allowed variable range to make this work?

Great work with the plugin BTW!

**Comment by nitaybz** [comment]
Update your homebridge version

**Comment by codyc1515** [comment]
The model number sounds like you are using the Bluetooth Tap with Wi-Fi dongle. If so, great! This device is supported. The message you are getting as well is just a warning as we add some additional Characteristics compared to what HomeBridge is expecting. This is not an error and is just a heads-up.

:)
