### ISSUE TITLE
Remaining Duration is not correct

### ISSUE THREAD

**Issue by codyc1515** [codyc1515/homebridge-orbit-bhyve#9]

**Comment by mitch7391** [comment]
The remaining duration on mine was correct when ran from the b-hyve app, the remaining duration in HomeKit reflected what I could see in the app.

**Comment by codyc1515** [comment]
Yes, as it should be. This is because we trust all of the input from there (how else would we get it?). However, the issue occurs when starting devices from the Home app. This is due to an odd design in the HomeKit spec which requires us to write our own timer logic. In some ways this makes sense, but in this instance it just makes it harder for the plug-in writer.

**Comment by mitch7391** [comment]
Sounds like a pain, is it worth raising to Orbit or Apple instead of having to do it yourself..?
